name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"  # Executa a cada 6 horas
  workflow_dispatch:  # Permite execução manual

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar a animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: 
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Commit e Push
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: output  # Pode mudar para gh-pages se preferir
          folder: dist

